// Team colors + logos, generated by scripts/build_data.py from ESPN.
import teamsJson from "../../data/teams.json";

export type TeamMeta = { name: string; color: string; logo: string; conf: string };
export const TEAMS = teamsJson as unknown as Record<string, TeamMeta>;

// Some school colors are near-black/near-white and vanish on the chart; nudge
// them toward mid-tones so every team line stays visible in both themes.
function readable(hex: string): string {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex);
  if (!m) return "#932F6D";
  let r = parseInt(m[1].slice(0, 2), 16), g = parseInt(m[1].slice(2, 4), 16), b = parseInt(m[1].slice(4, 6), 16);
  const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  if (lum < 40) { r += 70; g += 70; b += 70; }         // very dark -> lift
  else if (lum > 225) { r -= 55; g -= 55; b -= 55; }   // very light -> deepen
  const to = (x: number) => Math.max(0, Math.min(255, x)).toString(16).padStart(2, "0");
  return `#${to(r)}${to(g)}${to(b)}`;
}

export function teamColor(abbr: string): string {
  return readable(TEAMS[abbr]?.color ?? "#932F6D");
}
export function logoUrl(abbr: string): string {
  return TEAMS[abbr]?.logo ?? "";
}

// ── conference short names / ordering ────────────────────────────────────────
// Order matters: "Mid-American" must be tested before "American" (it contains it).
const CONF_SHORT_KEYS: [string, string][] = [
  ["Southeastern", "SEC"], ["Big Ten", "Big Ten"], ["Big 12", "Big 12"],
  ["Atlantic Coast", "ACC"], ["Pac-12", "Pac-12"], ["Mid-American", "MAC"],
  ["American", "American"], ["Mountain West", "Mtn West"], ["Sun Belt", "Sun Belt"],
  ["Conference USA", "C-USA"], ["Independent", "Independents"],
];
export function confShort(conf: string): string {
  for (const [key, short] of CONF_SHORT_KEYS) if (conf.toLowerCase().includes(key.toLowerCase())) return short;
  return conf;
}
export const CONF_ORDER = ["SEC", "Big Ten", "Big 12", "ACC", "Pac-12", "American", "Mtn West", "Sun Belt", "C-USA", "MAC", "Independents"];

// ── conditional-format scale ─────────────────────────────────────────────────
// Green above the mean, purple below, anchored to theme tokens so it reads in
// both light and dark mode. Center ~1500; span ±260 (CFB spreads wider than the pros).
export function eloTextColor(elo: number): string {
  const t = Math.max(-1, Math.min(1, (elo - 1500) / 260));
  if (Math.abs(t) < 0.05) return "var(--color-text)";
  const intensity = Math.round((0.4 + 0.6 * Math.min(1, Math.abs(t))) * 100);
  const anchor = t > 0 ? "var(--heat-green)" : "var(--heat-purple)";
  return `color-mix(in srgb, ${anchor} ${intensity}%, var(--color-text))`;
}

// Green fill for a probability cell (0..1).
export function oddsHeat(x: number): { bg: string; fg: string } {
  const a = Math.max(0, Math.min(1, x));
  return {
    bg: `color-mix(in srgb, var(--heat-green) ${Math.round(a * 78)}%, transparent)`,
    fg: a > 0.5 ? "#fff" : "var(--color-text)",
  };
}
